# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def fib(n)
  a, b = 0, 1
  (1 .. n).each do
    a, b = b, a + b
  end
  a
end

sum = 0
(1 .. 1.0/0).each do |i|
  term = fib(i)
  sum = sum + term if term % 2 == 0
  break if term > 4000000
end

puts sum
