# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

sum, a, b = 0, 0, 1
(1 .. 1.0/0).each do |i|
  a, b = b, a + b
  sum = sum + a if a % 2 == 0
  break if a > 4000000
end

puts sum
